replicaCount: 1
Image:
  repository: kpler/api
  tag: v1.0.0
  pullPolicy: Never
Service:
  name: nginx
  externalPort: 5000
  internalPort: 5000
  type: NodePort
Ingress:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  host: dev.kpler.com
